[project]
name = "pycon2025-chatbot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fastapi[standard]>=0.116.1",
    "openai>=1.99.9",
    "uvicorn>=0.35.0",
]
