services:
  # A Docker web service
  - type: web
    name: kakao-chat
    runtime: python
    plan: free
    autoDeploy: false
    buildCommand: pip install uv && uv pip sync
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
